name : Implementing CI for this repo

on:
    workflow_dispatch:
    push:
        branches:
          - main
          - 'feature/*'
env:
    MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: unit-testing
        strategy:
          matrix:
            os: [ubuntu-latest]
            node-version: [18] 
        runs-on: ${{ matrix.os}}
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: settingup node
              uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: installing dependices
              run: npm ci

            - name: running the unit test
              run: npm test

            - name: uploading the tests
              uses: actions/upload-artifact@v4
              with:
                name: unit test file
                path: test-results.xml
     
                
    code-coverage:
        name: code-coverage
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: settingup node
              uses: actions/setup-node@v4
              with:
                node-version: 18
            
            - name: installing dependices
              run: npm ci

            - name: running the code coverage
              run: npm run coverage
        
    docker:
       name: Conterinazation
       needs: [unit-testing,code-coverage]
       runs-on: ubuntu-latest
       steps: 
          - name: checkout repo
            uses: actions/checkout@v4

          - name:  Login to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ vars.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: building the image
            uses: docker/build-push-action@v6
            with:
              context: .
              push: false
              tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system/${{ github.sha }}

          - name: testing the image
            run: |
              docker images
              docker run solar-system -p 3000:3000 -e MONGO_URI=uriPlaceholder -e MONGO_USERNAME=usernamePlaceholder -e MONGO_PASSWORD=passwordPlaceholder ${{ vars.DOCKERHUB_USERNAME }}/solar-system/{{ github.sha }}
              curl localhost:3000



